#!/usr/bin/python
import random
import sys
import time
import os
def mengetik(s):
  for c in s + '\n':
    sys.stdout.write(c)
    sys.stdout.flush()
    time.sleep(random.random()*0.2)
mengetik('\033[1;35m   Jangan Lupa Bersyukur Pada ALLAH.')
